version: '3.9'

services:
  api:
    build:
      context: ../eccSchoolApp-api
      dockerfile: ../docker/go/Dockerfile
    container_name: api
    volumes:
      - ../eccSchoolApp-api:/go/src/app
    ports:
      - '8080:8080'

  web:
    build:
      context: ../eccSchoolApp-web
      dockerfile: ../docker/react/Dockerfile
    container_name: web
    volumes:
      - ../eccSchoolApp-web:/app
    ports:
      - '3000:3000'
    environment:
      - REACT_APP_API_URL=http://localhost:8080
    depends_on:
      - api